apiVersion: networking.k8s.io/v1.
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: distributed
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          io.kompose.network/distributed: "true"
  podSelector:
    matchLabels:
      io.kompose.network/distributed: "true"
