version: '3'
networks:
  distributed:
    internal: true
services:
  nginx:
    build: ./application/nginx
    ports:
     - "8080:8080"
    depends_on:
      #- frontend
      - backend
    networks:
      - distributed
  #frontend:
  #  build: ./application
   # ports:
   #   - "8080:8080"
   # depends_on:
    #  - backend
    #networks:
     # - distributed
  backend:
    build: ./application/api
   # ports:
    #  - "1337:1337"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root 
      - DATABASE_PASSWORD=password 
      - DATABASE_NAME=mydatabase 
    networks:
      - distributed
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
