version: '3'
networks:
 distributed:
  #  internal: true
services:
  db:
    restart: on-failure
    container_name: db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - distributed
  nginx:
    container_name: loadbalancer
    depends_on: 
    - backend
    - frontend
    restart: always
    build: ./application/nginx
    ports:
    - 81:80
    networks:
    - distributed
  frontend:
    container_name: frontend
    build: ./application
    ports:
     - "8080:8080"
    depends_on:
     - backend
    networks:
    - distributed
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    volumes:
    - grafana-storage:/var/lib/grafana
    networks:
    - distributed
  prometheus:
    build: ./prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--web.enable-lifecycle'
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
    - distributed
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports: 
    - 8081:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - db
    networks:
    - distributed
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
    - 9091:9091
    networks:
    - distributed
  backend:
    container_name: backend
    restart: always
    build: ./application/api
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
       DATABASE_PASSWORD: password 
       DATABASE_NAME: mydatabase 
       DATABASE_USER: mysql
       DATABASE_PORT: 3306
    networks:
      - distributed
volumes:
  mysql_data:
  grafana-storage:
  prometheus-data:
